spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: # TODO: put your email address.
    password: # TODO: put your email password.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true